%Fit binary decision tree for multiclass classification
dtree = fitctree(NumData,...
                 target,...
                 'MinParentSize',1,...
                 'MinLeafSize',1,...
                 'MaxNumSplits',5);
%classificationLearner()
%view(trainedModel1.ClassificationTree,'Mode','graph')
%view(dtree,'Mode','graph')